### ISSUE TITLE
Add new sub-domains with AWS named server (NS)

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/gsip#101]
Request from Naeem.

> Hello Gabriel, 
> 
> I am working with Eric to develop/migrate GSIP (https://geoconnex.ca/gsip/app/index.html) application to AWS and wanted to know if we can have a subdomain for our AWS networking and make an entry in the DNS provider for us: 
> 
> LDRS.geoconnex.ca 
> 
> I can provide you the NS records once I get confirmation from you. 
> 
> Thanks

@denevers

**Comment by ghuotvez** [comment]
After trying to find how it's being handled with EnomCentral, Naeem and me agreed to ask for support from their helpdesk.

**Comment by denevers** [comment]
This github repo is just for the code, not the infrastructure. I suggest you move this concern to internal gitlab.
Closing this ticket
