### ISSUE TITLE
Add multiple representation of info

### ISSUE THREAD

**Issue by denevers** [NRCan/GSIP#17]
Depending of the usage, multiple /info/ representations might be necessary.  The challenge and how to negotiate the a particular info for a given /id/.  Since /id/ there should be only one /id/ per real world feature in a given governance, the resolution to multiple /info/ cannot rely on the /id/ structure.

One can rely only on 

   * specialised format in the content negotiation (or subtype of formats, such as text/html; subtype=gin
   * profile negotiation (in http header)
   * parameters (profile=gin) 

or a combination of those options.

**Comment by jvanulde** [comment]
I don't understand the issue. Can't we rely on the `Accept` header?

**Comment by brodaric** [comment]
I believe this refers to the notion of having multiple representations of the info page – beyond format (syntax), which we already have. E.g. subsets of the links for specific use cases.  In our current approach this would require another level of re-direction – an info page to select the info page for a specific use case. Currently we assume an info page contains all, and we don’t allow profiles of info pages.

Is that the issue?

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>

**Comment by dblodgett-usgs** [comment]
I think we decided that we will not support multiple "profiles" of "info" pages/resources in SELFIE. Any additional version of the info page would be considered a representation of the NIR as far as we are concerned. If and when we have a good practice for content negotiation by profile _and_ we have a standard for "info" resources, then we would be able to use that mechanism to request profiles of the info resource.

**Comment by jvanulde** [comment]
Are we talking about different serializations of a resource (NIR)? Or, are we talking about metadata profiles?

**Comment by brodaric** [comment]
Different realizations of the metadata profile (link page)

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>

**Comment by dblodgett-usgs** [comment]
Since content negotiation only applies to the media-type (syntax) of a resource and not other ways to type a resource, we need more. @denevers uses "representation" to describe a wide-range of potential type-schemes. 

This issue is talking about having multiple "profiles" or other type-schemes that @brodaric can describe more thoroughly in addition to multiple media types.

**Comment by jvanulde** [comment]
> Strictly, according to [IETF 2616], HTTP reserves the term representation for entities that are subject to content negotiation. We'll use the term here the way it is used in [AWWW]. In this slightly broader sense, the term representation is used to mean the contents of a message which carries the essential characteristics of a resource, whether or not that material was subject to content negotiation.

[https://www.w3.org/2001/tag/doc/httpRange-14/2007-05-31/HttpRange-14](url)

Are we leaning more towards the AWWW rather than the IETF definition of representation?

**Comment by brodaric** [comment]
Yes, we are in the AWWW arena.

But broader – content (as per AWWW) typically refers to the semantics dimension, but I would  include structure and origin too.

Basic semiotic theory -  a sign (representation) has 4 dimensions: syntax, structure, semantics, source (agent). Actually there is a 5th (pragmatics) which is too complex to include here.

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>

**Comment by jvanulde** [comment]
Understood. Can we craft a use case for this? If not maybe we move it to the parking lot for now?

**Comment by dblodgett-usgs** [comment]
My comment above about SELFIE was meant to say -- we park this for now. We only support one "profile" of the info resource and move on till there is a compelling reason to do otherwise.

**Comment by denevers** [comment]
Or we support a single **default** profile (the one provided when no profile is specified - by a method yet to be identified), so some implementation (like GIN) could implement their own profile - known by given community - that does not break the default behavior.

**Comment by dblodgett-usgs** [comment]
That's fine, but it's unclear what you would be profil**ing**. If you want to invent your own mime-type and use normal content negotiation to get the special format you want, that seems fine but it would just be overloading the mime-type. If we really want to use content negotiation by profile at this stage, we'd be pretty far out on the bleeding edge, which I guess GIN has always been, so nothing new?

**Comment by denevers** [comment]
"yet to be identified". 

I suspect that the landing page could get rather long as the infrastructure grow.  One might just need specific properties that might be irrelevant for another application.

**Comment by dblodgett-usgs** [comment]
I can get on board with that... I do wonder if a profile of the info resource is a representation that would be referenced from _the_ info resource though.

**Comment by denevers** [comment]
such as an info resource shall point to all other known info profiles... good idea I think.

**Comment by jvanulde** [comment]
Closing for now. We can re-open when a concrete use case materializes.

**Comment by brodaric** [comment]
Current approach is to let the application decide what it needs to use, rather than pre-determine via profiles

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>

**Comment by brodaric** [comment]
Sorry for answering in pieces.

Additional profiling could be handled the same way, with another level of re-direction involving an additional url and hyperlink document – without requiring special http headers, etc. But we agreed to skip this complication for now. It can be document as an option in the final report.

Boyan

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>

**Comment by brodaric** [comment]
Conceivably yes, but would need to be very careful about differences:

One is a pointer to different metadata about the real thing (non-info resource)

The other is a pointer to different data about the real-thing.

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>
