### ISSUE TITLE
Establish a common ontology/vocabulary

### ISSUE THREAD

**Issue by jvanulde** [NRCan/GSIP#20]
Establish a common ontology/vocabulary for naming concepts and features. Consider HyFeatures.

**Comment by denevers** [comment]
Dave Bloggett already integrated HY_Feature.   I have an experimental version in ogc-onto branch

https://github.com/NRCan/GSIP/tree/ogc-onto/WebContent/repos/gsip

note the .imp file.. This was implemented to pull external files in Jena (could not make `owl:import` to work for some reason, )

**Comment by jvanulde** [comment]
Okay. Closing. See requirement #35.
