### ISSUE TITLE
Ontology loading error

### ISSUE THREAD

**Issue by jvanulde** [NRCan/GSIP#36]
On startup I am getting the following error:

    Failed to load /usr/local/tomcat/webapps/gsip/repos/gsip/ontology.ttl
    CHyLD | org.apache.jena.riot.RiotException: [line: 64, col: 1 ]
    Triples not terminated by DOT

**Comment by denevers** [comment]
as the error message says,, a dot was missing at the end of line 62

fix in commit 28f2d3aa4048b8c46d267878db67f1cd665ae8bf
