### ISSUE TITLE
Missing licence file?

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSIP#41]
The project could make a good use of an open source licence like some other public projects.

[https://github.com/NRCan/geo-deep-learning/blob/master/LICENSE](url)

There is also this thing
[https://open.canada.ca/en/open-government-licence-canada](url)

**Comment by ghuotvez** [comment]
The web template for federal website uses a slightly custom MIT licence
[https://github.com/wet-boew/GCWeb/blob/master/License-en.txt](url)

**Comment by jvanulde** [comment]
@tomkralidis do you have some guidance on what license we should use?

**Comment by tomkralidis** [comment]
We have used MIT and GPL3 given different contexts.  IMHO it depends on how the project feels about contributing back (GPL3) vs "do anything" (MIT).  The GoC license is also an option.

Whichever the case, it behooves any project to clearly identify the project's license (in full) in `LICENSE.md` at the root of the repo and shortened license headers in source code.

For non-source code (like docs), creative commons is an option.

**Comment by ghuotvez** [comment]
https://choosealicense.com/licenses/

**Comment by denevers** [comment]
As long as we have a statement that says "don't do any live threatening things with this code" or something, I'm fine

**Comment by jvanulde** [comment]
Added MIT License. Closing.
