### ISSUE TITLE
Provide more cross-border relations

### ISSUE THREAD

**Issue by jvanulde** [NRCan/GSIP#42]
In order to demonstrate the harvesting of linkages, there is an **immediate** need for more relations. Currently, there is one relation encoded in the harvester:

    <https://cida-test.er.usgs.gov/chyld-pilot/id/hu/041504081604>
    <https://www.opengis.net/def/hy_features/ontology/hyf/lowerCatchment>
        <https://geoconnex.ca/id/catchment/02OJ*CA>.

**Comment by dblodgett-usgs** [comment]
What other relations are we thinking here? If we are only working in the one watershed, I think this is more or less the only one that's available?

**Comment by denevers** [comment]
maybe other features? river segments ?

**Comment by dblodgett-usgs** [comment]
We won't be able to do anything in the **immediate**. Especially river segments since we have a unique-id conundrum with them still. Also, the catchment topology _is_ the river topology, so that is actually already expressed in the one we have. The only other thing I can think is to have a topological relationship between some aquifers across the boarder really.

**Comment by jvanulde** [comment]
It's going to be hard to demonstrate utility without a representative dataset. Can we prototype a single topological relationship to see how we might handle them?

**Comment by denevers** [comment]
yes.. good point.  We can discuss with Julie-Ann Ishikawa

**Comment by dblodgett-usgs** [comment]
Figured out how to add a few more. "segments" is hard since we don't have incremental flowpaths per HU12 but we _can_ do total-upstream flowpaths. Stay tuned, I think I'll have something deployed later today.

**Comment by dblodgett-usgs** [comment]
OK, we now have a few more. 

Several catchments [(such as this one)](https://cida-test.er.usgs.gov/chyld-pilot/info/hu/041504081007) overlap an aquifer. 

I also added a [nexus](https://cida-test.er.usgs.gov/chyld-pilot/info/hu_nexus/02OJ*CA-inflow) between the outlet of Lake Champlain and the first catchment in Canada.
