### ISSUE TITLE
USGS Harvesting Node Resource

### ISSUE THREAD

**Issue by jvanulde** [NRCan/GSIP#45]
As per https://geoconnex.ca/gsip/info/LOD_Node/CAN_Hydro_LOD_Node. 

We would like to demonstrate the harvesting and registration of linkages across nodes. In order to demonstrate this effectively, we need a connected node.

**Comment by dblodgett-usgs** [comment]
Can you point me to the setup for this end point? Some specific RDF or is it auto generated by a new version of GSIP?

**Comment by jvanulde** [comment]
@denevers can you provide some details on how you implemented please.

**Comment by denevers** [comment]
not today. urgent request from upper management

**Comment by denevers** [comment]
Here’s what I did:

1. I added a mime-type in the configuration + it’s mapped extension (to use with f= in HTML page) :  https://github.com/NRCan/GSIP/blob/master/WebContent/conf/configuration.xml (line 16)
2. I added the data for the node itself and related representations (/data/) : https://github.com/NRCan/GSIP/blob/master/WebContent/repos/gsip/nodes.ttl  in the repo folder.  This is loaded in RDF
3. Then I added a content-neg for /data/ to git repo you made : https://github.com/NRCan/GSIP/blob/master/WebContent/data/node.xml. You can see the regexp for each mime-type and parameters subsitutions (${p1} is the first item after /data/, etc..)

**Comment by denevers** [comment]
Step 3 is not required, you could use links directly to github at step 2. You would just end up with 3 representations each having 1 format instead of 1 representation with 3 format using /data/ conneg

**Comment by dblodgett-usgs** [comment]
https://cida-test.er.usgs.gov/chyld-pilot/id/LOD_Node/US_Hydro_LOD_Node

**Comment by denevers** [comment]
well done.  a `rdfs:label `assigned to `<https://cida-test.er.usgs.gov/chyld-pilot/id/LOD_Node/US_Hydro_LOD_Node>` would be a nice improvement

**Comment by jvanulde** [comment]
@denevers we should update our node with the new URI.

**Comment by denevers** [comment]
done

https://geoconnex.ca/gsip/info/LOD_Node/CAN_Hydro_LOD_Node

**Comment by dblodgett-usgs** [comment]
I fixed the label @denevers
