### ISSUE TITLE
Replace seeAlso to subjectOf

### ISSUE THREAD

**Issue by denevers** [NRCan/GSIP#49]
The property to link a NIR to a DIR should be schemas:subjectOf (from schemas.org)

https://schema.org/subjectOf

must replace in configuration, template, instance and javascript code that uses it to identify representations in the landing page

**Comment by denevers** [comment]
created a new branch 'selfie' to deal with changes from SELFIE meeting

**Comment by denevers** [comment]
commit 7e3a3a3def727b

**Comment by jvanulde** [comment]
👍
