### ISSUE TITLE
Améliorer le look des landing page

### ISSUE THREAD

**Issue by denevers** [NRCan/GSIP#55]
voir sur le staging: 

http://w-stf-a128913.nrn.nrcan.gc.ca/info/swmonitoring/MDDELCC_030415
et
http://w-stf-a128913.nrn.nrcan.gc.ca/gsip/info/LOD_Node/CAN_Hydro_LOD_Node

Les blocs de représentations sont pas très beaux

**Comment by denevers** [comment]
template to generate the landing page is in` WebContent/template/infohtml.ftl`

**Comment by heryk** [comment]
SVP réviser et fermer si c'est ok.

https://github.com/NRCan/GSIP/pull/69
