### ISSUE TITLE
Persist features in map

### ISSUE THREAD

**Issue by jvanulde** [NRCan/GSIP#64]
Make sure feature doesn't disappear when you select a new one.

**Comment by denevers** [comment]
Clarification for @heryk .  When we click on the "pin" to get a geojson representation on the map, the previous geojson is removed.  It would be good for demo purpose to keep them on the map and just add new geojson as they are pulled in.  At one point, it will be a mess, so maybe a quick solution is to have a "flush" button to clean the slate.

**Comment by heryk** [comment]
Done. I just sent a pull request from my fork

**Comment by heryk** [comment]
@denevers Validation: Once tested and if all is ok for you, you can close this ticket. Thanks

**Comment by heryk** [comment]
f43beae3a1c8482b5bcdb6f316bd842c2ef66428

**Comment by denevers** [comment]
works. thanks
