### ISSUE TITLE
Linking a non LOD app (CHyF) with GSIP

### ISSUE THREAD

**Issue by marklague** [NRCan/GSIP#8]
Currently there is a gap between CHyF pilote-project and GSIP when one wants to find the closest hydrometric station to a point or in a catchment for example.  One way is to fetch all the watersheds, get the geometry, find which one intersects our point and look for a relation with an hydrometric station.

Some alternatives are available and could help in simplifying the linkage between both application.

1. Add a geometric component on each item so that it can be searched via a GeoSPARQL query.
2.  Load the HUC 12 watersheds in the CHyF model.  Its ID would be used to access the LOD API and find the information needed.
3. Build an API on top of GSIP that takes a geometry and returns the ID of the watershed(s) that intersects it.
4. ...

We have to find out which solution is best suited for our needs.

**Comment by jvanulde** [comment]
@marklague @msondheim has this (option 2) been completed? I recall seeing the linkages in our recent demo.

**Comment by msondheim** [comment]
@jvanulde As you saw in the demo, this was done for the HUC12 equivalent watersheds in the Richelieu Valley. At this point in time, in Canada we generally do not have such watersheds defined. The closest would be the sub-sub-drainages from the Water Survey of Canada. The SSDs boundaries in the future could be adjusted with appropriate elevation and hydrographic data. Right now, they might be considered as useful approximations. Until we get some traction with CHyF operationally, the WSC folks are looking to make use of hydrosheds to create a general coverage. However, this still does not relate well to the HUC system. The Richelieu HUC12 equivalents were based (I think) on Quebec watersheds adjusted to fit the CHyF pilot catchment boundaries. Marie-Eve knows the details here.

**Comment by jvanulde** [comment]
@marklague please close this issue if it's been resolved.

**Comment by marklague** [comment]
@jvanulde I'll close the issue on GSIP side but I'll transfert it in the CHyF project since no solution exist yet on CHyF data that enables it to link with LOD.
