### ISSUE TITLE
Rework README

### ISSUE THREAD

**Issue by jvanulde** [NRCan/gsip#90]
Need to reflect the repository name change from GSIP to GeoConnex

**Comment by dblodgett-usgs** [comment]
sorry to be a pain... can we not camel case?

**Comment by jvanulde** [comment]
> sorry to be a pain... can we not camel case?

Not a problem. Actually broke our own internal naming convention. I've changed it.

**Comment by denevers** [comment]
Would it be better to create a new repo or reorganise this one in such a way that old GSIP java app is a sub section of this one ?

**Comment by jvanulde** [comment]
> Would it be better to create a new repo or reorganise this one in such a way that old GSIP java app is a sub section of this one ?

Possibly. We would have to move the issues though. I thought about it but I don't have permissions to create repo's in the NRCan org. We can create a new org called Geoconnex and have repos in there? @dblodgett-usgs what do you think?

**Comment by denevers** [comment]
Fair point.  I just wonder - if we use this to push new code - how to get the java app out of the way

**Comment by jvanulde** [comment]
Created new repo called geoconnex. I will move all the outstanding issues to that new repo.
