### ISSUE TITLE
Schema.org has River and Lakes

### ISSUE THREAD

**Issue by denevers** [NRCan/gsip#95]
Schema.org has types for some  water bodies

```
https://schema.org/LakeBodyOfWater
https://schema.org/RiverBodyOfWater
```

What's better ? assign both types to the resources

`<https://geoconnex.ca/id/waterbody/60c56a06be4911d892e2080020a0f4c9> a hy:HY_WaterBody,  schema:RiverBodyOfWater.`
or state the types are the same ?

`hy:HY_WaterBody owl:equivalentClass schema:RiverBodyOfWater.`

**Comment by brodaric** [comment]
I would assign both.

Conceptually they may not be the same.

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  ***@***.******@***.***>

From: Eric Boisvert ***@***.***>
Sent: March 19, 2021 11:47 AM
To: NRCan/gsip ***@***.***>
Cc: Brodaric, Boyan (NRCan/RNCan) ***@***.***>; Assign ***@***.***>
Subject: [NRCan/gsip] Schema.org has River and Lakes (#95)


Schema.org has types for some water bodies

https://schema.org/LakeBodyOfWater

https://schema.org/RiverBodyOfWater

What's better ? assign both types to the resources

<https://geoconnex.ca/id/waterbody/60c56a06be4911d892e2080020a0f4c9> a hy:HY_WaterBody, a schema:RiverBodyOfWater.
or state the types are the same ?

hy:HY_WaterBody owl:sameAs schema:RiverBodyOfWater.

**Comment by denevers** [comment]
The weird side effect of `owl:sameAs' will be that `hy:HY_WaterBody` will have a property `https://schema.org/smokingAllowed`

**Comment by denevers** [comment]
Indeed not conceptually the same.  in schema.org, they are kind of `schema:Place`
